# This rule is not used by the project op-stack-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over rollup.oplabs.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: op-stack-operator
    app.kubernetes.io/managed-by: kustomize
  name: opchain-admin-role
rules:
- apiGroups:
  - rollup.oplabs.io
  resources:
  - opchains
  verbs:
  - '*'
- apiGroups:
  - rollup.oplabs.io
  resources:
  - opchains/status
  verbs:
  - get
