---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - optimism.optimism.io
  resources:
  - opbatchers
  - opchallengers
  - opnodes
  - opproposers
  - optimismnetworks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - optimism.optimism.io
  resources:
  - opbatchers/finalizers
  - opchallengers/finalizers
  - opnodes/finalizers
  - opproposers/finalizers
  - optimismnetworks/finalizers
  verbs:
  - update
- apiGroups:
  - optimism.optimism.io
  resources:
  - opbatchers/status
  - opchallengers/status
  - opnodes/status
  - opproposers/status
  - optimismnetworks/status
  verbs:
  - get
  - patch
  - update
