## Append samples of your project ##
resources:
- optimism_v1alpha1_optimismnetwork.yaml
- optimism_v1alpha1_opnode.yaml
- optimism_v1alpha1_opnode_sepolia_replica.yaml
- optimism_v1alpha1_opbatcher.yaml
- optimism_v1alpha1_opproposer.yaml
- optimism_v1alpha1_opchallenger.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
