apiVersion: optimism.optimism.io/v1alpha1
kind: OptimismNetwork
metadata:
  labels:
    app.kubernetes.io/name: optimismnetwork
    app.kubernetes.io/instance: op-sepolia
    app.kubernetes.io/part-of: op-stack-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: op-stack-operator
  name: op-sepolia
  namespace: optimism-system
spec:
  # Network Configuration
  networkName: "op-sepolia"
  chainID: 11155420
  l1ChainID: 11155111

  # L1 RPC Configuration (required by all components)
  l1RpcUrl: "https://eth-sepolia.g.alchemy.com/v2/zeFYT4eQdrTCht4MM6BhQFqWzZ81QO8O"
  l1BeaconUrl: "https://sepolia-beacon.example.com"
  l1RpcTimeout: "10s"

  # Network-specific Configuration Files
  rollupConfig:
    autoDiscover: true  # Controller will generate rollup config

  l2Genesis:
    autoDiscover: true  # Controller will generate genesis config

  # Contract Address Discovery
  contractAddresses:
    discoveryMethod: "auto"  # auto, superchain-registry, well-known, manual
    cacheTimeout: "24h"
    
    # Optional: If you know the SystemConfig address, it helps with discovery
    systemConfigAddr: "0x034edD2A225f7f429A63E0f1D2084B9E0A93b538"

  # Shared Configuration for all components
  sharedConfig:
    # Logging
    logging:
      level: "info"
      format: "logfmt"
      color: false

    # Metrics
    metrics:
      enabled: true
      port: 7300
      path: "/metrics"

    # Resource Defaults (can be overridden by individual components)
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "1000m"
        memory: "2Gi"

    # Security
    security:
      runAsNonRoot: true
      runAsUser: 1000
      fsGroup: 1000
      seccompProfile:
        type: "RuntimeDefault"
