apiVersion: optimism.optimism.io/v1alpha1
kind: OptimismNetwork
metadata:
  labels:
    app.kubernetes.io/name: op-stack-operator
    app.kubernetes.io/managed-by: kustomize
  name: optimismnetwork-sample
spec:
  # Network configuration
  networkName: "op-sepolia"
  chainID: 11155420
  l1ChainID: 11155111
  
  # L1 configuration
  l1RpcUrl: "https://rpc.sepolia.org"
  l1BeaconUrl: "https://beacon.sepolia.org"
  l1RpcTimeout: 30s
  
  # Rollup configuration
  rollupConfig:
    autoDiscover: true
  
  # L2 Genesis configuration
  l2Genesis:
    autoDiscover: true
  
  # Contract address discovery
  contractAddresses:
    discoveryMethod: "auto"
    cacheTimeout: 1h
  
  # Shared configuration for all components
  sharedConfig:
    # Logging configuration
    logging:
      level: "info"
      format: "logfmt"
      color: false
    
    # Metrics configuration
    metrics:
      enabled: true
      port: 7300
      path: "/metrics"
    
    # Default resource requirements
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "2000m"
        memory: "4Gi"
    
    # Security configuration
    security:
      runAsNonRoot: true
      runAsUser: 1000
      fsGroup: 1000
      seccompProfile:
        type: RuntimeDefault
