//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BatcherConfig) DeepCopyInto(out *BatcherConfig) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BatcherConfig.
func (in *BatcherConfig) DeepCopy() *BatcherConfig {
	if in == nil {
		return nil
	}
	out := new(BatcherConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BatcherStatus) DeepCopyInto(out *BatcherStatus) {
	*out = *in
	if in.LastBatchSubmission != nil {
		in, out := &in.LastBatchSubmission, &out.LastBatchSubmission
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BatcherStatus.
func (in *BatcherStatus) DeepCopy() *BatcherStatus {
	if in == nil {
		return nil
	}
	out := new(BatcherStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentStatus) DeepCopyInto(out *ComponentStatus) {
	*out = *in
	if in.Geth != nil {
		in, out := &in.Geth, &out.Geth
		*out = new(GethStatus)
		**out = **in
	}
	if in.Node != nil {
		in, out := &in.Node, &out.Node
		*out = new(NodeStatus)
		**out = **in
	}
	if in.Batcher != nil {
		in, out := &in.Batcher, &out.Batcher
		*out = new(BatcherStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Proposer != nil {
		in, out := &in.Proposer, &out.Proposer
		*out = new(ProposerStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentStatus.
func (in *ComponentStatus) DeepCopy() *ComponentStatus {
	if in == nil {
		return nil
	}
	out := new(ComponentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentsConfig) DeepCopyInto(out *ComponentsConfig) {
	*out = *in
	in.Geth.DeepCopyInto(&out.Geth)
	in.Node.DeepCopyInto(&out.Node)
	in.Batcher.DeepCopyInto(&out.Batcher)
	in.Proposer.DeepCopyInto(&out.Proposer)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentsConfig.
func (in *ComponentsConfig) DeepCopy() *ComponentsConfig {
	if in == nil {
		return nil
	}
	out := new(ComponentsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContractAddresses) DeepCopyInto(out *ContractAddresses) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContractAddresses.
func (in *ContractAddresses) DeepCopy() *ContractAddresses {
	if in == nil {
		return nil
	}
	out := new(ContractAddresses)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GethConfig) DeepCopyInto(out *GethConfig) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
	out.Storage = in.Storage
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GethConfig.
func (in *GethConfig) DeepCopy() *GethConfig {
	if in == nil {
		return nil
	}
	out := new(GethConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GethStatus) DeepCopyInto(out *GethStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GethStatus.
func (in *GethStatus) DeepCopy() *GethStatus {
	if in == nil {
		return nil
	}
	out := new(GethStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L1Config) DeepCopyInto(out *L1Config) {
	*out = *in
	if in.ContractAddresses != nil {
		in, out := &in.ContractAddresses, &out.ContractAddresses
		*out = new(ContractAddresses)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L1Config.
func (in *L1Config) DeepCopy() *L1Config {
	if in == nil {
		return nil
	}
	out := new(L1Config)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeConfig) DeepCopyInto(out *NodeConfig) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeConfig.
func (in *NodeConfig) DeepCopy() *NodeConfig {
	if in == nil {
		return nil
	}
	out := new(NodeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeStatus) DeepCopyInto(out *NodeStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeStatus.
func (in *NodeStatus) DeepCopy() *NodeStatus {
	if in == nil {
		return nil
	}
	out := new(NodeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OPChain) DeepCopyInto(out *OPChain) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OPChain.
func (in *OPChain) DeepCopy() *OPChain {
	if in == nil {
		return nil
	}
	out := new(OPChain)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OPChain) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OPChainList) DeepCopyInto(out *OPChainList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OPChain, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OPChainList.
func (in *OPChainList) DeepCopy() *OPChainList {
	if in == nil {
		return nil
	}
	out := new(OPChainList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OPChainList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OPChainSpec) DeepCopyInto(out *OPChainSpec) {
	*out = *in
	in.L1.DeepCopyInto(&out.L1)
	in.Components.DeepCopyInto(&out.Components)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OPChainSpec.
func (in *OPChainSpec) DeepCopy() *OPChainSpec {
	if in == nil {
		return nil
	}
	out := new(OPChainSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OPChainStatus) DeepCopyInto(out *OPChainStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ContractAddresses != nil {
		in, out := &in.ContractAddresses, &out.ContractAddresses
		*out = new(ContractAddresses)
		**out = **in
	}
	if in.ComponentStatus != nil {
		in, out := &in.ComponentStatus, &out.ComponentStatus
		*out = new(ComponentStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OPChainStatus.
func (in *OPChainStatus) DeepCopy() *OPChainStatus {
	if in == nil {
		return nil
	}
	out := new(OPChainStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProposerConfig) DeepCopyInto(out *ProposerConfig) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProposerConfig.
func (in *ProposerConfig) DeepCopy() *ProposerConfig {
	if in == nil {
		return nil
	}
	out := new(ProposerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProposerStatus) DeepCopyInto(out *ProposerStatus) {
	*out = *in
	if in.LastProposal != nil {
		in, out := &in.LastProposal, &out.LastProposal
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProposerStatus.
func (in *ProposerStatus) DeepCopy() *ProposerStatus {
	if in == nil {
		return nil
	}
	out := new(ProposerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageConfig) DeepCopyInto(out *StorageConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageConfig.
func (in *StorageConfig) DeepCopy() *StorageConfig {
	if in == nil {
		return nil
	}
	out := new(StorageConfig)
	in.DeepCopyInto(out)
	return out
}
